# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  working_directory: /home/circleci
  docker:
    - image: circleci/node:8.12-stretch-browsers

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: echo fake test
      - persist_to_workspace:
          root: /home/circleci/packages/demo/component/lib

  npm_publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/packages/demo/component/lib
      - run: |
          echo $CIRCLECI_NPM_TOKEN >> ~/.npmrc
          npm publish

workflows:
  version: 2
  build:
    jobs:
      - build
  build_and_npm_publish:
    jobs:
      - build
      - npm_publish:
          filters:
            tags:
              only: /^react-utterances@.*/
          requires:
            - build
